# Generated by Django 3.2.3 on 2021-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('V', 'Vegetables'), ('OT', 'Others')], max_length=2),
        ),
    ]
