# Generated by Django 3.2.3 on 2021-05-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon1',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='icon2',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='icon3',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Fruits'), ('SW', 'Vegetables'), ('OW', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
